INFO       | 2017-05-10 21:06:24,884 __main__             | main                           |  311  | *************************************************
INFO       | 2017-05-10 21:06:24,884 __main__             | main                           |  312  | *                ae rabbitmq consumer           *
INFO       | 2017-05-10 21:06:24,884 __main__             | main                           |  313  | *************************************************
INFO       | 2017-05-10 21:06:24,885 __main__             | setup_with_connect_params      |  258  | [setup]
INFO       | 2017-05-10 21:06:24,897 __main__             | _submit_process_pool           |  212  | [submit process] i: 0, res_future: <Future at 0x7f263318ad68 state=running>, render_res_futures: {<Future at 0x7f263318ad68 state=running>}, render_worker: <__main__.RenderWorker object at 0x7f263318ad30>
INFO       | 2017-05-10 21:06:24,898 __main__             | _connect                       |  127  | [connect]
INFO       | 2017-05-10 21:06:24,903 pika.adapters.base_connection | _create_and_connect_to_socket  |  212  | Connecting to 127.0.0.1:5672
INFO       | 2017-05-10 21:06:24,908 pika.adapters.blocking_connection | __init__                       |  1099 | Created channel=1
INFO       | 2017-05-10 21:06:24,910 __main__             | run                            |  280  | [main running] pid 27402
INFO       | 2017-05-10 21:06:29,919 __main__             | _basic_get_render_request      |  180  | [basic_get] render_request: {'status': 'UnKnown', 'xpath': 'c:/footage/文件名.aepx', 'reply_to': 'render_response_rk'}
INFO       | 2017-05-10 21:06:39,933 __main__             | _process_render_result         |  225  | [process result] render_result: {'xpath': 'c:/footage/视频.mov', 'status': 'OK', 'reply_to': 'render_response_rk'}
INFO       | 2017-05-10 21:06:39,934 __main__             | _basic_publish_render_result   |  196  | [basic_publish] render_response: '{"xpath": "c:/footage/视频.mov", "status": "OK", "reply_to": "render_response_rk"}'
ERROR      | 2017-05-10 21:07:44,167 __main__             | run                            |  292  | [exception]
Traceback (most recent call last):
  File "ex_consumer.py", line 285, in run
    self._connection.sleep(self._config['rabbitmq_pull_interval'])
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 673, in sleep
    self.process_data_events(time_limit)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 650, in process_data_events
    self._flush_output(timer.is_ready, common_terminator)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/select_connection.py", line 590, in poll
    events = self._poll.poll(self.get_next_deadline())
KeyboardInterrupt
INFO       | 2017-05-10 21:07:44,170 __main__             | _disconnect                    |  141  | [disconnect]
INFO       | 2017-05-10 21:07:44,170 pika.adapters.blocking_connection | close                          |  1330 | Channel.close(0, Normal Shutdown)
INFO       | 2017-05-10 21:07:44,170 pika.channel         | close                          |  422  | Channel.close(0, Normal Shutdown)
INFO       | 2017-05-10 21:07:44,171 pika.adapters.blocking_connection | close                          |  616  | Closing connection (200): Normal shutdown
INFO       | 2017-05-10 21:07:44,171 pika.connection      | close                          |  731  | Closing connection (200): Normal shutdown
WARNING    | 2017-05-10 21:07:44,172 pika.connection      | _on_disconnect                 |  1360 | Disconnected from RabbitMQ at localhost:5672 (200): Normal shutdown
INFO       | 2017-05-10 21:07:44,172 pika.adapters.blocking_connection | _flush_output                  |  428  | Connection closed; result=BlockingConnection__OnClosedArgs(connection=<pika.adapters.select_connection.SelectConnection object at 0x7f2633197208>, reason_code=200, reason_text='Normal shutdown')
